name: LlamaDupe
main: fr.axel.llamadupe.LlamaDupePlugin
version: 1.0
author: axel
api-version: 1.21
commands:
  llamadupe:
    description: Active ou désactive la duplication de lama
    usage: /llamadupe <enable|disable>
    permission: llamadupe.admin
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande.
